jobapp/urls.py
from django.urls import path

from . import views

app_name='jobapp'


urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.admin1, name='upload'),
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapp/models.py
from django.db import models

# Create your models here.


class jobs_data(models.Model):
    job_Id = models.AutoField(primary_key=True)
    job_Name = models.CharField(max_length=100, blank=False, null=False )
    job_Company = models.CharField(max_length=100, blank=False, null=False)
    job_Location = models.CharField(max_length=100, blank=False, null=False)
    job_Desc = models.CharField(max_length=100, blank=False, null=False)
    

    class Meta:
        db_table = 'jobs' 

jobapp/views.py
from django.shortcuts import render
from .models import *
from jobproject.settings import BASE_DIR
# Create your views here.

def index(request):
    # jobs_data.objects.all().delete() #To Delete the data
    jobs = jobs_data.objects.all()
    return render(request, 'index.html', {'jobs':jobs, 'BASE_DIR':BASE_DIR})


def admin1(request):
    if request.method == 'POST':
        job = jobs_data()
        job.job_Name = request.POST.get("job_Name", False)
        job.job_Company = request.POST.get("job_Company", False)
        job.job_Location = request.POST.get("job_Location", False)
        job.job_Desc = request.POST.get("job_Desc", False)

        job.save()

    
    return render(request, 'upload.html')

jobapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Job Listing Site</title>
    
</head>
<body>
    
 
    <div style="margin: 150px;">
        <h1>Job Listing Site</h1>
        <h3>Developed by Ria Ann Bijo 22112033</h3>
        {% for job in jobs %}

        <div class="card mb-3">
            
            <div class="card-body">
              <h5 class="card-title">{{job.job_Name}}</h5>
              <p class="card-text">{{job.job_Company}}</p>
              <p class="card-text">{{job.job_Location}}</p>
              <p class="card-text"><small class="text-muted">{{job.job_Desc}}</small></p>
            </div>
          </div>

 {% endfor %}

 <a href="{% url 'jobapp:upload' %}">
    <button>Add Job</button>
</a>

    </div>




    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>

jobapp/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Job Listing Site</title>
</head>
<body>
 
    <div style="margin: 150px;">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="job_Name">Job Name</label>
              <input type="name" class="form-control" name="job_Name" id="job_Name" aria-describedby="emailHelp" placeholder="Enter Job Name">
            
            </div> <br>

            <div class="form-group">
              <label for="job_Company">Company Name</label>
              <input type="text" name="job_Company" class="form-control" id="job_Company" placeholder="Enter Company name">
            </div> <br>

            <div class="form-group">
                <label for="job_Location">Job Location</label>
                <input type="text" name="job_Location" class="form-control" id="job_Location" placeholder="Enter job location">
              </div> <br>
            <div class="form-group">
                <label for="job_Desc">Job Description</label>
                <input type="text" name="job_Desc" class="form-control" id="job_Desc" placeholder="Enter job description">
              </div> <br>

              

            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="{% url 'jobapp:index' %}">Home Page</a>
          </form>  

    </div>




    
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    
</body>
</html>